name: Run

on: [pull_request]

jobs:
  install:
    name: install app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: '@esolidar'

      - name: Install dependencies
        run: yarn --pure-lockfile --production=false
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

  lint:
    name: Run code lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          node-version: 12
          path: ./*
          key: ${{ github.sha }}
      - run: yarn test:lint

  allPass:
    name: Well done
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - run: exit 0
