name: build

on:
  push:
    branches: ['main', 'testing']

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com
          scope: '@esolidar'

      - name: Install dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Run lint tests
        run: yarn test:lint
